### ISSUE TITLE
Change sub-classes in the detail pane of active/recorded timer items

### ISSUE THREAD

**Issue by BradConnor** [chri55w/QuickBooks-Timer#29]
If the class and service item fields in the timer detail pane were selectable, that would let me keep just several high-level timer types in my selectable list which I can then fine-tune in the individual line items. For example, I would like one "NHS-FV BusDev" timer type, which I use for customer visits, logging proposal requests, sales emails, etc. I don't want to have to have individual timer types for each and every one of those, the list would quickly become unmanageable. For the "NHS-FV Development" time type, for example, I could have six different sub-types; I just want one timer type, not six!

![timer detail](https://cloud.githubusercontent.com/assets/18011157/14177146/d8ea8914-f74c-11e5-891d-e053988d114c.JPG)

**Comment by chri55w** [comment]
This could be quite a complicated change, Given the current application structure I would say its almost impossible. I'll have a think about it but this certainly wont be an easy change if its even workable at all.

**Comment by chri55w** [comment]
Following some rather drastic Data re-structuring for the application I will be looking to work this in in the following way:
- User will create a Timer Type as normal, This will be essentially a template for the time Logs it produces
- When the user clicks Start to Generate a new Time Log the Time Log will be given all the Details of the Timer Type to store within itself rather than currently just containing the Timer Type reference.
- This will then allow any Element within the Time Log to be modified without any knock on effects as it will be entirely self contained.

**Comment by BradConnor** [comment]
Cool

**Comment by chri55w** [comment]
In order to accomodate this change and also for general improvement reasons I have modified the formatting for the editing panel, this will also be useful in the changes required for #21 (Dynamic Tiers for Customers and Service Items)

Since dynamic tiers will not be implemented for the next release this change will be modified to use the current two tier system

![image](https://cloud.githubusercontent.com/assets/10941226/14383690/9ac54c1c-fd8e-11e5-8e45-da9e43be7951.png)

**Comment by chri55w** [comment]
Using the approach shown in #21 (due to the changes required to fit its needs) i have modified the Time Log Edit panel as shown below, the three fields 'Customer', 'Service Item' and 'Class' all use the new Hierarchy structured ComboBox as seen in the second image. Improvements have been made to the Styling of the panel to better display the Billable status and improve styling consistency when the TimeSpanPicker control is disabled (third image)

![image](https://cloud.githubusercontent.com/assets/10941226/14468854/a3c8a2c0-00d9-11e6-93a4-a17bf27f7a2e.png)

![image](https://cloud.githubusercontent.com/assets/10941226/14468868/c1ccbd42-00d9-11e6-96b9-373eeed22cb6.png)

![image](https://cloud.githubusercontent.com/assets/10941226/14468935/0ee6985a-00da-11e6-96bf-81035486786d.png)
